[JD-55] 예약 확정, 취소 API
prgrms-be-devcourse/BE-03-java-and-dining pull request #26
Opened 2023-01-19 18:29 UTC by preferKim

⭐️ 좋은 코드 리뷰는 친절한 PR로 부터 나옵니다! 모두들 꼼꼼히 작성해주세요. ⭐️

## 개발 내용
> 수정 or 추가, 개발된 내용에 대해서 1줄로 간단히 작성합니다.

API 개발 

* (점주) 확정 대기 상태의 예약을 확정하는 API 

```java
// 요청
PATCH http://localhost:8080/owner/api/reservations/{reservationId}/confirm?ownerId={ownerId}

// 정상 응답
HTTP/1.1 200 

<Response body is empty>

// 비정상 응답
HTTP/1.1 400 

{
  "httpStatus": "BAD_REQUEST",
  "errorMessage": "리소스를 수정할 수 없습니다."
}
```

* (점주) 확정 대기 또는 확정 상태의 예약을 취소하는 API 

```java
// 요청
PATCH http://localhost:8080/owner/api/reservations/{reservationId}/cancel?ownerId={ownerId}

// 정상 응답
HTTP/1.1 200 

<Response body is empty>

// 비정상 응답
HTTP/1.1 400 

{
  "httpStatus": "BAD_REQUEST",
  "errorMessage": "리소스를 수정할 수 없습니다."
}
```

## 집중적인 코드리뷰
> 좀 더 상세하게 리뷰 받고 싶은 부분을 기재해주세요.

* `Reservation` 엔티티, `ReservationTest` 위주로 봐주시면 감사하겠습니다.
- `예약 확정 또는 취소는 방문시간 이전까지만 가능하다.` 라는 비즈니스 정책을 잘 지켜졌는지 궁금합니다. 
- validation 부분에 대한 로직이 어색하지 않은지, 가독성이 좋은지 궁금합니다.

`resources/generated-requests.http` 로 E2E 테스트가 가능합니다!

## 리마인더
* 본인의 로컬에서 정상 동작하는지 확인해주세요.
* 최신 브랜치를 Pull 받고 PR을 요청했는지 확인해주세요.
* **API**가 추가되었을 경우 테스트를 하고 PR을 올려주세요.
* **Conflict**가 났을 때, UI상에서 해결하지 말고, 본인 local에서 해결해주세요.
* **commit 메시지** 제대로 작성해주세요.

2023-01-19 18:31 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
🧑‍💻 예약 엔티티가 스스로 상태를 변경하기 위해, 비즈니스 정책에 맞는 유효성 검사를 진행합니다.

2023-01-19 18:35 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
🧑‍💻 예약 엔티티의 `status`를 변경하기 전에, 유효한 값인지 검증합니다.
(예: 예약을 확정하기 위해서 `status` 가 `PENDING` 이어야함)

2023-01-19 18:41 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	private void assertMatchesOwner(Long ownerId) {
🧑‍💻 Spring 이 제공하는 `Assert` 의 메서드가 특정한 조건을 충족하지 못하면 그 즉시 예외를 발생시키는 것에서 착안하여, 
비슷한 구조를 가지는 메서드를 `assertXXX`  처럼 네이밍하였습니다.

2023-01-19 18:47 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
🧑‍💻 예약 방문 시간이 기준 시간 이후인지를 검증하는 로직입니다. 
에약을 확정 또는 취소하기 위해서는 방문 시간이 현재 시간 이후여야 하므로 이렇게 작성해봤습니다. 
현재 시간은 해당 메서드를 호출할 때 인자로 전달합니다.

2023-01-19 18:51 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/FakeReservationCustomerInput.java
> +public class FakeReservationCustomerInput extends ReservationCustomerInput {
🧑‍💻 예약 확정, 취소와 관련한 테스트를 작성하기 위해 구현한 Fake 객체입니다. 프로덕션 코드는 최대한 변경사항이 없게하기 위해 유효성 검증 메서드의 접근 제어자만 변경하도록 하였습니다.

2023-01-20 06:51 UTC, hwankim123 requested changes
선호님 고생하셨습니다! 

말씀 주신대로 비즈니스 정책을 잘 지켜서 코딩했는지를 위주로 코드리뷰 해보았습니다!

2023-01-20 06:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationStatusUpdateService.java
> +		}
a: rethrow를 해주셨군요! 승훈님 얘기를 듣고 나니, rethrow도 꼭 필요한 경우에 하는 것이 맞다고 생각이 드네요.

지금 단계에서는 넘어가도 좋을 것 같은데, 다음 스프린트 때 꼭 rethrow가 필요한지 얘기할 필요가 있을 것 같아요!

2023-01-20 06:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		assertVisitDateTimeAfter(TimeUtils.getCurrentSeoulDateTime());
a: TimeZone이 있는 DateTime 클래스를 사용하셨네요! 
지금 제 코드로는 간단하게 LocalDateTime을 사용하는데, 둘중에 어떤 것을 사용하면 좋을지 고민해봐야 할 것 같아요.

2023-01-20 06:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		assertVisitDateTimeAfter(TimeUtils.getCurrentSeoulDateTime());
r: 그리고 지금 정책상 `예약 당일에는 어플리케이션을 통해 예약을 취소할 수 없다`고 정한 것 같아요. 이 코드대로라면 당일 예약도 취소가 될 것 같습니다. 

위 코드에서 예약 취소를 하루 전날까지만 가능하게 수정하려면 파라미터를 `TimeUtils.getCurrentSeoulDateTime().minusDays(1L)` 처럼 바꿔야 할 것 같은데요, 이런 방식은 좀 깔끔하지 않은 것 같아요.
아래처럼 ReservationCustomerInput이 취소 가능한 시간을 계산하는 책임까지 같이 갖게 해주면 어떨까요?
```
private boolean isLateToCancel(LocalDate cancelDate) {
  return cancelDate.isAfter(
	  visitDate.minusDays(1L)
  );
}
```

2023-01-20 08:20 UTC, Tnfls99 reviewed
선호님 안녕하세요. 이번에 리뷰를 맡게 된 이수린입니다 ☺️

실패 케이스까지 모두 테스트로 작성해주셔서 
마치 하나의 요구사항 문서를 읽는 느낌이 들었습니다. ㅎㅎ
정말 고생많으셨습니다!!

요구사항을 대부분 다 만족하고 있는 것 같아 몇 가지만 소소하게 달아봤습니다!
잘 부탁드립니다!!

2023-01-20 08:20 UTC, Tnfls99 commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/ReservationTest.java
> +	@DisplayName("확정 대기 또는 확정 상태의 예약을 취소 상태로 변경할 수 있다.")
r: 현재는 점주만 예약을 취소할 수 있는 것 같아요. 

저희 요구사항에 고객도 예약 확정 전이면서, 방문하기 전날까지 취소가 가능한 것으로 알고 있는데, 이것은 반영이 아직 안된 것일까용?

2023-01-20 08:20 UTC, Tnfls99 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	private void assertVisitDateTimeBefore(LocalDateTime dateTime) {
c: 지금 이 코드는 사용을 안하고 있는 것 같은데 확인 한번 부탁드려요!

2023-01-20 08:20 UTC, Tnfls99 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		if (!this.customerInput.isVisitDateTimeBefore(dateTime)) {
c: 저는 개인적으로 if 문 내에서 `!`를 사용하는 것이 가독성이 좋지 않아 보여서
한 가지 방향으로 어떤 여부를 판단하는 메소드를 사용할 경우에는 `isNot`, `is`로 메소드에 명시해주고는 합니다! 

현재의 경우 isVisitDateTimeBefore가 visitDate가 dateTime보다 before이지 않으면 예외가 발생하는 경우에 대해서만 사용이 되고 있기 때문에 isVisitDateTimeNotBefore 정도로 바꿔볼 수 있을 것 같아요 (:

선호님은 어떻게 생각하시는지 궁금합니다 ㅎㅎ

2023-01-20 08:20 UTC, Tnfls99 commented on src/main/java/com/prgms/allen/dining/global/util/TimeUtils.java
> +	}
a: 자주 사용되는 시간 메소드를 따로 유틸 클래스로 뺀 것이 아주 인상적이에요 !! 👍

2023-01-20 21:15 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	private void assertVisitDateTimeBefore(LocalDateTime dateTime) {
다음 구현 시에 필요했던 메서드라 생각해서 미리 작성해두었는데, 기우였던 것 같네요😅
당장 필요한 메서드외에는 정리하는 습관을 들여나가야겠습니다. 감사합니다 :)

2023-01-20 21:51 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		if (!this.customerInput.isVisitDateTimeBefore(dateTime)) {
현재 메서드의 경우 `org.springframework.util.Assert` 의 `if(!expression) throws XXXException` 구조를 차용하였는데요, 특정 조건(비즈니스 정책)을 만족시키지 못하는 경우 예외를 발생시킨다는 점이 맘에 들어 if 문에 자연스럽게 `!` 을 포함하게 된 것 같습니다. 

수린님 말씀처럼 현재 메서드가 하나의 유즈케이스에서만 제한적으로 사용되므로 굳이 `!` 를 사용해야할까라는 것에 공감이 되었고, 추가적으로 찾아본 바, 

> [메서드가 하나의 유즈 케이스에서만 사용될 경우 메서드 명에 not이 포함되어도 괜찮다.
> 다만 재사용성을 고려하여 메서드명을 긍정형으로 짓는 것이 권장된다.](https://levelup.gitconnected.com/knot-of-nots-avoiding-negative-names-for-boolean-methods-641896a94a42)

라는 내용이 있더군요! 다만 저는 재사용성을 떠나 메서드명에 not 을 포함시키는 순간부터 중복 부정의 모호함이 생길수 있다는점에서 우선 현재대로 유지할 것 같습니다. 

사실 이 부분은 전혀 고려해보지 못했던 부분이었어요. 인사이트 감사합니다 :)

2023-01-20 21:54 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/ReservationTest.java
> +	@DisplayName("확정 대기 또는 확정 상태의 예약을 취소 상태로 변경할 수 있다.")
맞습니다. 현재는 점주만 고려하여 반영했는데 `DisplayName` 이 이 부분을 명시적으로 드러내지 못하고 있었네요😅
반영해서 수정해보겠습니다!

2023-01-20 21:58 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		assertVisitDateTimeAfter(TimeUtils.getCurrentSeoulDateTime());
이 부분도 오늘 모각코 때 얘기를 나누었는데요, 

정리해보자면 
- 애플리케이션이 EC2 인스턴스에서 배포되므로 EC2 만 Asia/Seoul 로 설정해주면 프로덕션 코드에서는 별도의 시간대 설정이 필요없다.
- EC2 인스턴스에 MySQL을 설치할 경우 DB 시간대는 별도의 설정이 필요하다. 

정도로 요약되는 것 같습니다! 🥳

2023-01-20 22:09 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationStatusUpdateService.java
> +		}
맞습니다. 사실 rethrow 를 서비스 레이어에서 할 것인가 자체도 고민해봐야할 것 같네요. 
위 같은 경우 `IllegalModificationException`가 내부적으로는 `HttpStatus`를 알고있으므로 rethrow 를 컨트롤러에서 해주는 편이  더 좋을 것 같긴합니다 🤔

2023-01-20 22:21 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		assertVisitDateTimeAfter(TimeUtils.getCurrentSeoulDateTime());
구현할 때 `당일 취소 불가능` 부분을 미처 고려하지 못했네요😭

제안해주신 로직이 고객 쪽에서도 활용하기 좋아보입니다. `isLateToCancel` 네이밍 역시 의도가 분명히 드러나서 저희 정책에 딱일 것 같습니다. 

수정하고 다시 멘션 남기겠습니다!💪

2023-01-21 00:26 UTC, preferKim reviewed
@hwankim123 @Tnfls99 
리뷰 반영하였습니다! 확인 후 슬랙 메시지나 코멘트 남겨주시면 바로 머지하도록 하겠습니다!

2023-01-21 00:26 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/ReservationCustomerInput.java
>  	}
Fix: DateTime 비교에서 Date 비교로 변경하여, '예약 당일 취소가 불가능' 하도록 수정하였습니다!

2023-01-21 00:26 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/ReservationTest.java
> +	@DisplayName("점주는 확정 대기 또는 확정 상태의 예약을 취소할 수 있다.")
행위의 주체가 조금 더 명시적으로 드러나도록 DisplayName 을 수정하였습니다. 추후 고객이 예약을 취소하는 경우도 같은 로직을 쓰게되면 해당 부분을 다시 손보도록 하겠습니다!

2023-01-21 05:51 UTC, Tnfls99 commented
@preferKim 선호님 확인하였습니다! 고생하셨습니다!!!👍

2023-01-21 05:51 UTC, Tnfls99 approved these changes

2023-01-22 00:43 UTC, merged