[JD-58] 예약 방문 완료, 노쇼 로 변경
prgrms-be-devcourse/BE-03-java-and-dining pull request #36
Opened 2023-01-23 05:56 UTC by preferKim

⭐️ 좋은 코드 리뷰는 친절한 PR로 부터 나옵니다! 모두들 꼼꼼히 작성해주세요. ⭐️

## 개발 내용
> 수정 or 추가, 개발된 내용에 대해서 1줄로 간단히 작성합니다.

* 고객의 방문시간 이후, 점주가 확정상태를 방문완료/노쇼 로 변경하는 API 를 구현합니다.

예약을 방문 완료로 변경
```java
// request
PATCH /owner/api/reservations/{reservationId}?ownerId={ownerId} HTTP/1.1

{"status":"visit"}

// response
HTTP/1.1 200 OK
```

예약을 노쇼로 변경
```java
// request
PATCH /owner/api/reservations/{reservationId}?ownerId={ownerId} HTTP/1.1

{"status":"no-show"}

// response
HTTP/1.1 200 OK
```

## 집중적인 코드리뷰
> 좀 더 상세하게 리뷰 받고 싶은 부분을 기재해주세요.

- `Reservation`, `ReservationCustomerInput`, `ReservationTest` 에 구현한 비즈니스 정책 위주로 봐주시면 감사하겠습니다.
  ```plain
  - 예약 방문 시간부터 예약 상태 변경이 가능
  - 방문일을 포함한 날짜로부터 30일 이내 상태 변경 가능
  ```
- E2E 테스트가 가능합니다. 단 API 호출로 방문시간이 지난 예약을 생성할 수 없기 때문에, 이 경우 응답으로 `400`을 내려줍니다.
 정상 호출 케이스는 REST Docs `resources/static/index.html` 에서 확인 가능합니다.

## 리마인더
- [x] 본인의 로컬에서 정상 동작하는지 확인해주세요.
- [x] 최신 브랜치를 Pull 받고 PR을 요청했는지 확인해주세요.
- [x] **API**가 추가되었을 경우 테스트를 하고 PR을 올려주세요.
- [x] **Conflict**가 났을 때, UI상에서 해결하지 말고, 본인 local에서 해결해주세요.
- [x] **commit 메시지** 제대로 작성해주세요.

## 코드리뷰 룰
* R(Request Change): 해당 블럭은 꼭 변경해주셨으면 좋겠습니다.
* C(Comment): 웬만하면 고려해주시면 좋겠습니다.
* A(Approve): 반영해도 좋고 넘어가도 좋습니다. 혹은 사소한 의견입니다.

2023-01-23 06:17 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
🧑‍💻 확정 상태의 예약을 방문완료로 변경합니다. 

- 예약의 식당의 점주의 식별자를 확인합니다.
- 현재 status 를 확인합니다. 
- 방문시간이 현재시간 이전인지 확인합니다.
- 현재날짜가 방문일로부터 30일 이내인지 확인합니다.

2023-01-23 06:17 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/web/domain/owner/reservation/OwnerReservationApi.java
>  	) {
🧑‍💻 요청 상태 변경 URI에서 상태 변경 행위 (예: confirm) 를 JSON으로 입력받도록 수정하였습니다.

- URI 를 처음 설계 시, 예약 상태 변경 API의 HTTP 메서드가 POST, PATCH로 구분되어 별개의 메서드로 설계하였습니다. 그러나 저희 애플리케이션에서  `Reservation` 의 `status` 에만 리소스 수정이 발생하므로 모든 메서드를  PATCH로 사용하게 되었고, 이에 완전히 같은 플로우를 같는 로직을 하나의 API 메서드로 리팩토링 하게 되었습니다.
- 이전 URI 의 경우 쿼리 스트링에 예약 상태를 변경하는 행위가 명시되어, URI 수정만으로 실제 리소스가 변경되는 문제가 있었습니다. Payload 를 통해서만 `변경할 예약 상태`를 확인함으로써 이같은 문제를 해결하였습니다.

2023-01-25 08:02 UTC, hwankim123 requested changes
선호님! 구현해주신 코드들 잘 확인했습니다! 정책에 맞게 잘 구현해주신 것 같아요.

몇가지 리뷰를 남겨드렸는데요, 완료 & 노쇼뿐만 아니라 다른 상태변경 로직에도 해당되는 내용이니만큼 선호님의 의견이 궁금합니다.

고생하셨습니다!! 😉

2023-01-25 08:09 UTC, yewon9609 reviewed
선호님 안녕하세요. 리뷰어 서예원입니다☺️
코드를 너무 잘 작성해주셔서 제가 말씀드릴게 별로 없네요 (아쉽..)
특히  entity에 비즈니스 로직을 넣으신 부분보면서 저도 많이 배웠습니다 
Assert또한 너무 잘 사용하신 것 같아요 ! 
고생하셨습니다 ~!

2023-01-25 08:09 UTC, yewon9609 commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/ReservationTest.java
> +	}
`c`: 테스트 코드내에서 아래의 코드가 계속 반복되는것 같은데 BeforeEach()로 묶는건 어떨까요?
```
Member owner = memberRepository.save(DummyGenerator.OWNER);
Restaurant restaurant = restaurantRepository.save(DummyGenerator.createRestaurant(owner));
Member customer = memberRepository.save(DummyGenerator.CUSTOMER);
```

2023-01-25 08:12 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/ReservationCustomerInput.java
> +
앗 이코드는 사실 상당부분 제가 작성한겁니다 🤣

저는 습관적으로 변수들을 사용하기 직전에 초기화하곤 하는데, 그 부분이 읽어내리기 편하다고 느껴져서였습니다. 예원님 생각은 어떠신가요?

2023-01-25 08:16 UTC, yewon9609 commented on src/main/java/com/prgms/allen/dining/web/domain/owner/reservation/OwnerReservationApi.java
> +			case "no-show" -> reservationStatusUpdateService.noShow(reservationId, ownerId);
(지나가다가🤭) 저도 이부분 Enum 활용을 생각해봤는데요, 
Enum클래스에서 Service를 알게되어야 할 것 같은데 그 부분에 대해서는 어떻게 생각하시나요🤔?

2023-01-25 08:31 UTC, yewon9609 commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/ReservationCustomerInput.java
> +
앗 🤣 
아까 코드를 읽어내려가면서 다시 위로 올렸던지라 한번에 위치해놓으면 더 편할것같다고 느꼈습니다 !

2023-01-25 09:13 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
저 역시 환님처럼 코드 상으로 비즈니스 정책을 1대1 로 매핑해야하나(`assertVisitDateToVisit`) 하는 지에 대해 한참을 고민했던 것 같습니다. 특히 `"상태를 변경하기 위해서" 메서드 호출 시 "파라미터에 들어가야 할 값"이 정책과 관련한 값들인 것`에 많이 공감이 되네요. 실제로 정책 상 `LocalTime.now(), LocalDateTime.now()` 역시 `ReservationCustomerInput`에 있어도 무방하다고 생각해서 처음에는 `assertDaysBetweenCurrentDateAndVisitDateWithin(...)` 같은 메서드를 작성했었거든요.

다만, `코드 상으로 비즈니스 정책을 1대1 로 매핑`하는 것은 그 자체로 절차지향적이라고 생각해요. 이렇게 될 경우 Api 메서드 호출 부터 ReservationCutomerInput 의 어느 메서드를 호출할 것인가 까지 1대1로 매핑이 되어버리니까요(물론 엔티티의 필드를 수정하는 요구사항에 따라 API 호출 부터 `visit()` 까지 현재 1대1로 매핑되어 있긴 해요). 

 그래서 저는 비즈니스 정책을 구현하기 위해 각 객체의 책임에 맞는 메서드를 구현해놓고, 이것을 조합하여 정책을 구현했습니다(물론 필요한 로직을 순서대로 호출하는 `visit(Long ownerId)` 내부는 절차지향적일 수 밖에 없죠).

그럼 이제 정책을 알고 있는 책임이 `Reservation`이냐 아니냐를 생각해봐야하는데, `방문일자 이후 어느 기간까지 예약 상태를 변경할 수 있는가?(=MAX_STATUS_UPDATE_EXPIRATION_PERIOD)` 를 알아야 하는 책임은 `Reservation`에 있다고 생각했어요. `CustomerInput`은 VO로써, `Reservation` 이 갖는 Status 에 대해서는 알면 안 된다고 생각했기 때문이에요.(물론 코드상으로 의존하지 않게끔 구현 가능하지만 이미 메서드명부터 ReservationsStatus 를 내포하고 있으니까요). 

덕분에 다시 한 번 OOP에 대해 고민을 해볼 수 있었습니다. 이 부분은 차후에 대화를 나눠보며 더 공부해보자구요!💪

2023-01-26 02:33 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
이렇게 구현한 것은 방문일자 이후 어느 기간까지 예약 상태를 변경할 수 있는가?(=MAX_STATUS_UPDATE_EXPIRATION_PERIOD) 를 알아야 하는 책임은 Reservation에 있다고 생각했기 때문인데요, CustomerInput은 VO로써, Reservation 이 갖는 Status 에 대해서는 알면 안 된다고 판단했거든요.(물론 코드상으로 의존하지 않게끔 구현 가능하지만 이미 메서드명부터 ReservationsStatus 를 내포하고 있으니까요).

본 리뷰 덕분에 어제 팀원들끼리 모여 추가적으로 이 외에도 예외처리에 대한 책임, 최종 결정권자(객사오의 판사-증인 예시 중) 등 OOP에 대한 다양한 관점들을 경험할 수 있어 너무 좋았습니다. 감사합니다!

2023-01-26 02:56 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +			getRestaurantOwner().matchesId(ownerId),
확실히 `restaurant` 의  `owner_id` 만 필요한데, 불필요하게 `member` 테이블도 조인하는 문제가 있군요! 
다만 현재 컨텍스트는 `이 예약에 매핑된 점주의 식별자가 ownerId 와 일치하는가` 에 해당해서  `member` 를 join 하지 않는 방법이 있을까 고민되네요.

해당 부분도 어제 환님과 함께 의견을 나눠봤는데요, 정리하자면 

- Join 을 하지 않게 하기 위해서 `@OneToOne(fetch = FetchType.LAZY)` 를 사용하여 select 문 2번으로 대체 
![image](https://user-images.githubusercontent.com/65555299/214748108-87704ead-f46f-4992-ac09-9d64154e0348.png)
- 점주 id 필드를 예약 엔티티에 추가하여 객체 참조를 끊는 방법 

정도의 방법이 있었네요🧐 

구현에만 집중했지, 쿼리문이 어떻게 나가는가는 충분히 고려하지 못했었는데 덕분에 다시 한 번 생각해볼 수 있게 되었어요. 감사합니다!

2023-01-26 03:21 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/web/domain/owner/reservation/OwnerReservationApi.java
> +			case "no-show" -> reservationStatusUpdateService.noShow(reservationId, ownerId);
@hwankim123 @yewon9609 

해당 리뷰를 오늘 스크럼 시간에 다뤄봤는데요, 정리하자면

- 기존 작성한 `ReservationStatus`의 열거상수를 그대로 사용
- 기존 작성한 `ReservationStatus`의 열거상수에 웹을 위한 필드 추가 
- 상수를 정의하는 용도의 private 생성자를 가진 클래스 
- 전략 패턴 사용 

정도로 요약해볼 수 있었어요. 

또한 

- '기존 작성한 `ReservationStatus`의 열거상수에 웹을 위한 필드 추가' 의 경우:
 웹을 위한 코드를 도메인에 작성하게됨 
- '상수를 정의하는 용도의 private 생성자를 가진 클래스'의 경우:
 정책 네이밍이 변경될 경우 코드 수정이 2군데 이상 일어남
 - 전략 패턴 사용: 
Enum 처럼 서비스 코드를 사용하는 것이 일종의 전략패턴(전략 열거 패턴)으로 볼 수도 있을 것 같아요.([Item34- int 상수 대신 열거 타입을 사용하라](https://jjingho.tistory.com/81)) 다만 현재 Enum 전략 패턴을 써서 서비스 코드를 직접 호출하게 되면 의존하는  방향이 어색해질 수 있겠네요(예원님 의견처럼요).
 
 결론 
 
환님 의견처럼 ReservationStatus 의 열거 상수를 그대로 사용해도 좋을 것 같습니다. 물론 열거 상수가 과거형 단어라는 것이 조금 걸리긴 하지만 이 역시 REST Docs로 헷갈리지 않게 드러낼 수 있겠어요.

2023-01-26 03:22 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +		validUpdatableReservationState(ownerId, CONFIRMED);
validate 로 작성한다고 작성했는데 valid 로 되어있네요 🤣 (아마 꿈속에서 작성했나봅니다..)

놓쳤던 부분인데 세심하게 봐주셔서 감사드려요!

2023-01-26 03:32 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/ReservationCustomerInput.java
> +				MAX_RESERVE_PERIOD
아마 기존에 작성된 코드와 통일되게 하기 위해 이렇게 작성한 것 같네요. 말씀대로 현재 코드에서 int 로 변경해도 전혀 문제될 게 없을 것 같습니다👍
int 대신 long 을 쓰는 기준을 얘기해봐도 좋을 것 같은데요, 저는 엔티티 식별자에 관습적으로 `Long` 을 쓰는 것 외에는 일반적으로 int 를 사용하고 있긴 합니다. 예원님은 어떻게 기준을 정하시는지 궁금합니다🧐

2023-01-26 04:01 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/domain/reservation/entity/ReservationTest.java
> +	}
`BeforeEach()` 를 사용하면 확실히 코드 중복을 줄일 수 있어 말씀해주신 것 같아요. 다만 `테스트 메서드 내 필요한 자원을 모두 명시해야한다.` 라고 생각해요. 물론 이렇게 되면 `DummyGenerator` 역시 사용을 지양해야 되겠죠. 따라서 엔티티 객체 생성에 대한 것만 `DummyGenerator`이 담당하고, `Repository` 에 엔티티 객체를 저장하는 코드를 테스트 메서드에 남김으로써 `저장된 엔티티 객체` 라는 문맥정보를 줄 수 있게 구성하였어요. 

정리하자면,
 테스트 메서드 하나만을 보고 어떤 선후관계가 필요한지 알 수 있으면(스크롤 역시 필요없죠😎), 중복이어도 괜찮다고 생각합니닷!

2023-01-26 05:09 UTC, yewon9609 submitted a review, later dismissed

2023-01-26 05:36 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/web/domain/owner/reservation/OwnerReservationApi.java
> +		}
이 부분에 대해 예원님과 함께 대화를 나눠봤는데요, 

위 코드를 서비스 객체에 넣어 `reservatoinStatusUpdateService.update(RequestDTO)` 처럼 작성하면 확실히
`컨트롤러 코드를 최대한 깔끔하게 유지`할 수 있겠네요.

덕분에 새로운 인사이트를 알게되었어요! 감사합니다!☺️

2023-01-26 09:08 UTC, preferKim reviewed
@yewon9609 @hwankim123 

리뷰 반영하여 코멘트 남겼습니다! 확인 부탁드려요!

2023-01-26 09:08 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationStatusUpdateService.java
> +	}
- 예약 상태 변경 로직의 분기를 더 이상 컨트롤러가 아닌 서비스가 담당합니다.
- 분기 조건인 매직 스트링을 열거 상수로 대체하였습니다.

2023-01-26 09:08 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/entity/Reservation.java
> +	}
- `ReservationCutomerInput`이 가졌던 예외 처리 책임을 `Reservation`이 갖도록 수정하였습니다. (예약 상태 변경의 최종 결정권이 있는 객체는 Reservation 이기 때문입니다.)

2023-01-26 09:53 UTC, yewon9609 approved these changes

2023-01-26 09:56 UTC, hwankim123 approved these changes
확인했습니다! 고생하셨습니다~

2023-01-26 09:56 UTC, merged