[JD-11, JD-10] 구매자 예약 관련 조회 API
prgrms-be-devcourse/BE-03-java-and-dining pull request #37
Opened 2023-01-25 12:12 UTC by dlxortmd987

⭐️ 좋은 코드 리뷰는 친절한 PR로 부터 나옵니다! 모두들 꼼꼼히 작성해주세요. ⭐️

## 개발 내용
> 수정 or 추가, 개발된 내용에 대해서 1줄로 간단히 작성합니다.

다음 2가지를 개발했습니다!
* 구매자의 예약을 상세 조회하는 API (JD-11)
* 구매자의 예약 목록을 조회하는 API (JD-10)

## 집중적인 코드리뷰
> 좀 더 상세하게 리뷰 받고 싶은 부분을 기재해주세요.

* 메서드 네이밍을 한번 봐주시면 좋을 것 같아요!

## 리마인더
- [x] 본인의 로컬에서 정상 동작하는지 확인해주세요.
- [x] 최신 브랜치를 Pull 받고 PR을 요청했는지 확인해주세요.
- [x] **API**가 추가되었을 경우 테스트를 하고 PR을 올려주세요.
- [x] **Conflict**가 났을 때, UI상에서 해결하지 말고, 본인 local에서 해결해주세요.
- [x] **commit 메시지** 제대로 작성해주세요.

## 코드리뷰 룰
* R(Request Change): 해당 블럭은 꼭 변경해주셨으면 좋겠습니다.
* C(Comment): 웬만하면 고려해주시면 좋겠습니다.
* A(Approve): 반영해도 좋고 넘어가도 좋습니다. 혹은 사소한 의견입니다.

2023-01-27 02:51 UTC, hwankim123 reviewed
택승님! 코드 잘 보았습니다. 요구사항에 맞게 잘 구현해주신 것 같아요!

리뷰 내용은 컨벤션 등과 같은 자잘한 내용들이니 가볍게 확인해주세요!

2023-01-27 02:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +	// TODO: Owner 정보 추가하기
c: TODO가 남아있네요 🤣 Owner 정보는 추가 하셨을까요??

2023-01-27 02:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		//ownerId
c: 이 Service 메서드에 ownerId는 필요하지 않아서 생략이 되었을까요? 
고객용 메서드에는 customerId를 받고 있어서 질문드립니다!

2023-01-27 02:51 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/dto/RestaurantInfoRes.java
> +public record RestaurantInfoRes(
a: 네이밍이 Restaurant로 시작해서 Reservation 도메인의 DTO인지 살짝 햇갈리는 것 같아요.

저희 팀 컨벤션으로 DTO를 그룹화하기 위해 멤버 클래스를 활용하지 않는다고는 하였는데, 이런 경우에는 `ReservationDetailRes`에서 멤버로 갖고있어도 괜찮아 보이네요. 한번 팀원들끼리 컨벤션에 대해 얘기해볼까요?

2023-01-28 10:15 UTC, preferKim requested changes
@dlxortmd987 

안녕하세요 택승님, 리뷰어 김선호입니다! 

API 호출부터 리포지토리 레이어까지의 플로우를 따라가며 리뷰를 진행했는데요, 
API 가 정상동작하는 것을 확인했고, 비즈니스 정책을 구현한 부분에서도 특별히 이상한 점은 발견하지 못하였습니다. 코드를 읽으면서, 택승님의 수려하게 스트림과 JPA를 활용하시는 점을 보며 저도 많이 배워갈 수 있었어요.

간단하게(?) 리뷰를 남겼으니, 확인해주시면 감사하겠습니다. 고생하셨습니다!

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/domain/reservation/dto/VisitStatus.java
> +
C: `방문 상태를 3개로 나누어 관리한다` 역시 저희 비즈니스 정책으로 볼 수 있을 것 같아요. 그렇게 되면 `VisitStatus` 역시 reservaton.entity 패키지 또는 reservation 패키지에 위치하게 하는 것이 조금 더 자연스러운 것 같은데 택승님은 어떻게 생각하시나요?🤔  (비록 `VisitStatus` 가 거의 DTO를 위한 코드로써 사용되더라도 의미상으로 패키지를 구분해도 좋을 것 같아서요!)

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/global/error/exception/NotFoundResourceException.java
> +	}
A: 텔레스코핑 생성자 패턴에서, 매개변수가 더 적은 생성자를 매개변수가 더 많은 생성자 위에 위치시켜보는 것은 어떨까요? [이펙티브 자바 아이템2. 생성자에 매개변수가 많다면 빌더를 고려하라 (p.14)](https://da-nyee.github.io/posts/effective-java-item-2/) 의 텔레스코핑 생성자 패턴 예제처럼, 매개변수가 더 많은 생성자가 코드상 더 아래에 있는 것이 가독성이 좋다고 느껴서요☺️

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
A: 메서드명만봐서는 특정 식당이 가지고 있는 모든 예약을 조회하는 것으로 느꼈어요. 다만 실제로는 고객별 & 방문상태별로 조회하고 있고, 식당 정보는 활용하지 않는 것으로 보입니다. 이 메서드는 `복수의 예약건을 조회하는데, 고객별 & 방문상태별로 조회한다` 라는 느낌을 살려 `getReservationsByCustomerAndVisitStatus` 정도로 표현해도 좋을 것 같습니다! 

ps. 메서드명이 너무 구체적이고 길지 않나라는 느낌이 들었지만, 이 메서드는 generic 하게 쓰이는 메서드가 아니라서 오히려 더 구체적이어도 된다고 생각해요!

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
C: `예약 단건 조회, 다건 조회, 상태별 조회` 등 예약을 조회하는 기능 자체가 꽤 되는 것 같아서 `ReservationQueryService` 처럼 별도의 서비스 객체로 분리해도 좋을 것 같은데 택승님은 어떻게 생각하시는지 궁금합니다. 지난 번 예원님께서 공유해주신 자료 - ["(기록) 한 개의 메소드만 갖는 계층형 컨트롤러/서비스 패키지 스타일"](https://johngrib.github.io/wiki/article/hierarchical-controller-package-structure/)를 읽고 아이디어를 얻었는데,  해당 포스팅처럼 서비스당 하나의 단일 메서드를 갖게끔하기에는 현재로서 다소 무리가 있겠지만 앨런님 말씀처럼 기능별로 서비스 객체를 분리해도 좋을 것 같아서요!

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +	public ReservationDetailRes getReservationDetail(Long reservationId, Long customerId) {
![image](https://user-images.githubusercontent.com/65555299/215258076-8d622816-e7ff-4b33-bc6e-f8474c429498.png)

A: 이 메서드는 현재 고객-예약 API 에서만 사용되고 있는 것으로 확인되는데요, 식당-예약 API에서 이 메서드를 재활용하지 않는다면 `getCustomerReservationDetail` 처럼 용도를 구분해볼 수 있을 것 같습니다!

2023-01-28 10:15 UTC, haero77 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +			)));
R: 예외 메시지가 리포지토리의 메서드를 못 따라가고 있는 것 같습니다. 

이 예외는 DB에 컬럼 `reservation_id`와 `customer_id`을 동시에 만족시키는 튜플이 없을 때 발생하는 것으로 이해하고 있어요.

그렇다면 해당 예외 메시지로 인해 실제로 `reservation_id` 와 매핑되는 엔티티가 있음에도 불구하고, 자칫 엔티티가 없는 것으로 오해할 수 있을 것 같습니다.

`Cannot find Reservation entity satisfies both reservationId={0} and customerId={1}` 처럼 수정함으로써 더 정확한 정보 전달과 함께 디버깅하기도 더 쉬워질 것 같습니다!

2023-01-28 10:15 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/domain/member/FakeMemberRepository.java
> +			.findFirst();
C: 현재 로직에서는 객체의 동일성 비교가 아니라 동등성만 비교해도 될 것 같아요. 
`Objects.equals()` 는 내부적으로 객체의 주솟값을 먼저 비교하고 그 다음 `Object.equals()` 를 호출하므로, 동등성 비교만 하도록 `Object.equals()`로 대체해봐도 좋을 것 같습니다!


- 참고
[자바의 동일성과 동등성](https://steady-coding.tistory.com/534)
[Objects.equals() Vs. Objects.equals()](https://stackoverflow.com/questions/34486832/objects-equals-and-object-equals)
![image](https://user-images.githubusercontent.com/65555299/215260238-428dd32b-0833-4ca8-adad-6cf3f4208cd6.png)

2023-01-28 10:15 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/web/customer/reservation/CustomerReservationApiTest.java
> +
A: 사용하지 않는 주석인 것 같습니다!

2023-01-28 10:15 UTC, preferKim commented on src/test/java/com/prgms/allen/dining/web/customer/reservation/CustomerReservationApiTest.java
> +	private ReservationRepository reservationRepository;
A: 개인적으로는 어노테이션이 붙은 필드끼리는 한 줄씩 띔으로써 가독성이 더 좋아짐을 느꼈습니다!

2023-01-28 10:52 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +	// TODO: Owner 정보 추가하기
이 부분이 인가가 완료되면 다음으로 추가할 계획이었습니다 😅
지금부터 넣을지는 고민이 되네요..ㅎㅎ

2023-01-28 10:53 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		//ownerId
레스토랑 id 로 받을지 아니면 점주 id 로 받을지 고민을 했는데 이 부분은 레스토랑을 받도록 설계를 했습니다!
고객용 메서드와 비슷하게 점주 id 로 바꾸면 더 통일성이 있을까요?
환님의 의견을 듣고싶습니다!

2023-01-28 10:54 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/dto/RestaurantInfoRes.java
> +public record RestaurantInfoRes(
좋습니다! 저도 이부분이 참 고민이었는데요. 일단 `Info` 가 붙은 키워드는 DTO 내부의 DTO 로 설계를 했습니다!
멤버 클래스를 고려하도록 얘기를 해봐야겠네요!

2023-01-28 10:56 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +	// TODO: Owner 정보 추가하기
앗 그런거라면 이해했습니다!👌

2023-01-28 10:56 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/dto/VisitStatus.java
> +
저도 이 클래스를 어디에 넣을지 고민을 했었는데요. 
선호님 말씀대로 비즈니스 정책에 가까우니 entity 패키지에 넣는게 더 좋아보이는 것 같습니다!
좋은 의견 감사드립니다! 😀

2023-01-28 10:57 UTC, hwankim123 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		//ownerId
사실 이부분은 제가 권한 관련한 로직을 아직 완성하지 않아서 애매한 것 같습니다... 일단은 1차 MVP 선에서 정상적으로 동작한다면 문제는 없을 듯 싶습니다.

2023-01-28 10:58 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/global/error/exception/NotFoundResourceException.java
> +	}
아하 이부분은 신경쓰지 못했는데 선호님 말씀대로 바꿔보니 더 읽기가 좋아진 것 같습니다!
반영해볼게요~

2023-01-28 11:00 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
> A: 메서드명만봐서는 특정 식당이 가지고 있는 모든 예약을 조회하는 것으로 느꼈어요. 다만 실제로는 고객별 & 방문상태별로 조회하고 있고, 식당 정보는 활용하지 않는 것으로 보입니다. 이 메서드는 `복수의 예약건을 조회하는데, 고객별 & 방문상태별로 조회한다` 라는 느낌을 살려 `getReservationsByCustomerAndVisitStatus` 정도로 표현해도 좋을 것 같습니다!
> 
> ps. 메서드명이 너무 구체적이고 길지 않나라는 느낌이 들었지만, 이 메서드는 generic 하게 쓰이는 메서드가 아니라서 오히려 더 구체적이어도 된다고 생각해요!

저도 메서드 네이밍에서 레스토랑을 빼면 좋을 것 같다는 생각이 드네요!
다만 저는 개인적으로 메서드 시그니쳐로 충분히 표현을 할 수 있다고 생각이 들어서요!
혹시 선호님 생각은 어떠신가요?

2023-01-28 11:02 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +	public ReservationDetailRes getReservationDetail(Long reservationId, Long customerId) {
날카로운 지적 감사합니다! 
선호님이 말씀해주신 것처럼 이후 점주 입장에서의 api 로도 활용이 예상되어
메서드 네이밍을 지어봤습니다!

2023-01-28 11:04 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +			)));
선호님이 꼼꼼하게 체크해주셔서 다행이네요~ 
중간에 메서드가 바뀌었는데 에러 메시지는 수정하지 못했네요..😅
이 부분은 수정해보겠습니다!

2023-01-28 11:09 UTC, dlxortmd987 commented on src/test/java/com/prgms/allen/dining/domain/member/FakeMemberRepository.java
> +			.findFirst();
개인적으로 `member.getId()` 가 null 일 경우를 생각해서
 `Objects.equals()` 를 사용했습니다!

선호님이 리뷰를 남기신 것을 보고 다시 생각해보니 null 일 수가 없다고 생각이 드네요.
선호님이 제시하신 의견처럼 이 부분은 동등성만 비교해도 되니 
`Object.equals()` 를 이용해보면 좋겠네요!

2023-01-28 11:10 UTC, dlxortmd987 commented on src/test/java/com/prgms/allen/dining/web/customer/reservation/CustomerReservationApiTest.java
> +	private ReservationRepository reservationRepository;
한 줄씩 떼어야 겠네요 ㅎㅎ
감사합니다~!😆

2023-01-28 11:31 UTC, dlxortmd987 commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
> 

조회 쪽만 서비스를 분리해봐도 좋겠군요! 너무 좋은 것 같습니다!
예원님이 공유해주신 자료를 한번 제대로 읽어봐야 겠네요! 감사합니다!

2023-01-28 11:34 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
저도 다시 돌이켜보니, 확실히 리포지토리 레이어의 메서드만큼 구체적일 필요가 있을까? 라고 생각해보면 그보다는 추상적이어도 되겠다고 느꼈습니다. 택승님 말씀처럼 메서드 시그니처로 표현되니까요. 다만 예약 다건 조회가 고객용, 점주용으로 나뉘는 만큼 `getCustomerReservations`, `getOwnerReservations` 정도는 표현해도 좋을 것 같아요.

2023-01-28 11:43 UTC, preferKim commented on src/main/java/com/prgms/allen/dining/domain/reservation/ReservationService.java
> +		final List<ReservationStatus> statuses = status.getStatuses();
> > A: 메서드명만봐서는 특정 식당이 가지고 있는 모든 예약을 조회하는 것으로 느꼈어요. 다만 실제로는 고객별 & 방문상태별로 조회하고 있고, 식당 정보는 활용하지 않는 것으로 보입니다. 이 메서드는 `복수의 예약건을 조회하는데, 고객별 & 방문상태별로 조회한다` 라는 느낌을 살려 `getReservationsByCustomerAndVisitStatus` 정도로 표현해도 좋을 것 같습니다!
> > ps. 메서드명이 너무 구체적이고 길지 않나라는 느낌이 들었지만, 이 메서드는 generic 하게 쓰이는 메서드가 아니라서 오히려 더 구체적이어도 된다고 생각해요!
> 
> 저도 메서드 네이밍에서 레스토랑을 빼면 좋을 것 같다는 생각이 드네요! 다만 저는 개인적으로 메서드 시그니쳐로 충분히 표현을 할 수 있다고 생각이 들어서요! 혹시 선호님 생각은 어떠신가요?

저도 다시 돌이켜보니, 확실히 리포지토리 레이어의 메서드만큼 구체적일 필요가 있을까? 라고 생각해보면 그보다는 추상적이어도 되겠다고 느꼈습니다. 택승님 말씀처럼 메서드 시그니처로 표현되니까요. 다만 예약 다건 조회가 고객용, 점주용으로 나뉘는 만큼 `getCustomerReservations`, `getOwnerReservations` 정도는 표현해도 좋을 것 같아요.

2023-01-29 20:59 UTC, preferKim approved these changes
변경사항 확인하였습니다! 고생많으셨습니다!

2023-01-29 20:59 UTC, merged